### ISSUE TITLE
Exception has occurred: NameError name 'unicode' is not defined

### ISSUE THREAD

**Issue by dezchai** [jduncan8142/ClassicUPS3#1]
Hi I get

'Exception has occurred: NameError
name 'unicode' is not defined'

When trying to do anything with the UPS api. Is this an error on my end?

**Comment by jduncan8142** [comment]
Late reply I know but figured I'd check if you ever figured out this issue. If you are still having need for this and error please post full output with error and I'll attempt to help.

**Comment by adeanadean** [comment]
Hi I realize this is a closed discussion and I am posting this about 2 years after. But I also am getting the NameError name 'unicode' is not defined when I try to use this UPS package.

Thank you!
